
#Chao Chen G01476331
#Vue image
# Build stage
FROM node:18 AS build-stage
# Chao Chen G01476331
# Vue image

# Build Stage
FROM node:18-alpine AS builder
WORKDIR /app
COPY . .
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:stable-alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Production Stage
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx config with reverse proxy
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
