apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/4SQsc7bIBSF3+XOdmIb2/HP3LFDpy5Vhgtc1zQYENxEiiLevaJRo0qN2hEO59N3eABG+5VStsGDBIwxH289NHCx3oCETxRduO/kGRrYidEgI8gHoPeBkW3wuR6D+kGaM/Eh2XDQyOzoYMPRVsg8DqIfSLR6UNiOUz+2OOHaDkYMQnRinRVBacChIvdP3IZ5Awkn/BjJzLpTRvTiJFRH3XQap2XRs5rXZehoWc1HX6EedwIJ+ZpudG8V6gt5A8/7HFHX0NCKV8f1eY6kq0Gi6KzGDLJvIJMjzSHVYEfW2+eXKcb4N72UBpj26JDpV+ePj3P/r/520MEzWk8pg/z2ALvj92qrNwx6Iz/Ox7er3q2NIfGT8oJ+CYlBLt3Sl3M5l1LKzwAAAP//V7JIpw0CAAA
    objectset.rio.cattle.io/id: 642312e3-c2ba-4514-a5af-2d323303f6be
  creationTimestamp: '2025-07-22T20:47:27Z'
  generation: 1
  labels:
    objectset.rio.cattle.io/hash: 7a94ed6c0bd31373b0e0574588c6b6f820e8fd91
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"survey-backend"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":8081,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: agent
      operation: Update
      time: '2025-07-22T20:47:27Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2025-07-22T20:47:35Z'
  name: survey-backend
  namespace: default
  resourceVersion: '262248'
  uid: c6fa2473-8e5b-45ab-a7a0-dbcf9e2f957c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: survey-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: survey-backend
    spec:
      containers:
        - image: chaochen46/survey-backend
          imagePullPolicy: Always
          name: survey-backend
          ports:
            - containerPort: 8081
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2025-07-22T20:47:35Z'
      lastUpdateTime: '2025-07-22T20:47:35Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2025-07-22T20:47:27Z'
      lastUpdateTime: '2025-07-22T20:47:35Z'
      message: ReplicaSet "survey-backend-677d85896" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
