apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-fronted
  template:
    metadata:
      labels:
        app: survey-fronted
    spec:
      containers:
      - name: vue-frontend
        image: chaochen46/survey-frontend:proxy
        ports:
        - containerPort: 80
