apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-frontend
  namespace: default
  labels:
    app: survey-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-frontend
  template:
    metadata:
      labels:
        app: survey-frontend
    spec:
      containers:
        - name: survey-frontend
          image: chaochen46/vue-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
