apiVersion: v1
kind: Service
metadata:
  name: survey-backend-service
  labels:
    app: survey-backend
spec:
  type: ClusterIP
  selector:
    app: survey-backend
  ports:
    - port: 8081        
      targetPort: 8081 
      protocol: TCP
